apiVersion: v1
kind: Pod
metadata:
  name: giropops
spec:
  containers:
    - name: girus
      image: ubuntu
      resources:
        limits:
          memory: 200Mi
          cpu: 0.2
      args:
        - sleep
        - infinity
      volumeMounts:
        - name: primeiro-emptydir
          mountPath: /giropops
  volumes:
    - name: primeiro-emptydir
      emptyDir:
        sizeLimit: 256Mi