apiVersion: v1
kind: Pod
metadata:
  name: my-pod-with-private-image
spec:
  containers:
  - name: my-private-custom-nginx
    image: danilomr12/my-custom-nginx:0.1
    resources:
      limits:
        memory: 200Mi
        cpu: 0.4
  imagePullSecrets:
  - name: docker-hub-secret